//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stockss
    {
        public int StoID { get; set; }
        public string Availabilit { get; set; }
        public Nullable<int> ProID { get; set; }
    
        public virtual Emp Emp { get; set; }
    }
}
